version: "3.9"

services:
  react-app:
    build:
      context: . # Use the current directory to build the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    restart: always # Automatically restart the container if it stops
