name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Get short SHA
      id: get_short_sha 
      run: echo ::set-output name=SHORT_SHA::$(git rev-parse --short ${{ github.sha }})

    # Cache Docker layers for faster builds
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Build the Docker image
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }} # Don't push on PR
        tags: |
          ${{ steps.meta.outputs.tags }},
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_short_sha.outputs.SHORT_SHA }}
        # tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
